### ISSUE TITLE
In Tree.Navigate.restructure, state.path is reversed

### ISSUE THREAD

**Issue by christianp** [lue-bird/elm-rosetree-path#1]
It's taken me an hour to work out why this happens, but I don't think I'm able to come up with a way of fixing it.

In `Tree.Navigate.restructure`, the `state` object for a given tree node is built from the bottom up. This means that the `path` property is reversed, because the `Tree.Path.toChild` calls happen in reverse order.

I've made [a small example on Ellie](https://ellie-app.com/ntcLMFj9hYKa1). Here's the code:

```
module Main exposing (main)

import Browser
import Html as H exposing (Html)
import Tree
import Tree.Path as TP
import Tree.Navigate as TN


test_tree = Tree.tree "top" 
    [ Tree.tree "0" 
        [ Tree.singleton "0, 0"
        , Tree.singleton "0, 1"
        ]
    , Tree.tree "1" 
        [ Tree.singleton "1, 0"
        , Tree.tree "1, 1" 
            [Tree.singleton "1, 1, 0"]
        , Tree.singleton "1, 2"
        ]
    ]

view_item sub = 
    H.div
        []
        [ H.text <| Debug.log "reduce" <| sub.label++" : "++(Debug.toString sub.path)
        , H.ul
            []
            (List.map (\c -> H.li [] [c]) sub.children)
        ]


view model =
    TN.restructure view_item test_tree


main : Program () () msg
main =
    Browser.sandbox
        { init = ()
        , view = view
        , update = \_ -> identity
        }
```

Is this intended behaviour?

**Comment by lue-bird** [comment]
Thanks so much for reporting, and thanks for the SSCCE! A fix is published now.

Shame on me, I actually noticed that a bug existed in `restructure` paths during my last game jam but forgot to fix the base version :sweat_smile:,
so sorry for the hour this took from you.

**Comment by christianp** [comment]
That was quick, thanks! I suppose since you know that `TreePath` is a list, it's OK to just prepend to it and not refer to a function in `Tree.Path`.

**Comment by lue-bird** [comment]
That's exactly what I did in the fix, yeah.
